export { default as CoachRegisterHeader } from './CoachRegisterHeader'
export { default as CoachAccountInfoSection } from './CoachAccountInfoSection'
export { default as CoachPersonalInfoSection } from './CoachPersonalInfoSection'
export { default as CoachPrivacyPolicySection } from './CoachPrivacyPolicySection'
export { default as CoachRegisterActions } from './CoachRegisterActions'